local _G = GLOBAL

_G.STRINGS.CHARACTERS.MIOTAN = require "speech_wortox"
_G.STRINGS.CHARACTER_SURVIVABILITY.miotan = _G.STRINGS.CHARACTER_SURVIVABILITY.wortox

-- -- book --
_G.STRINGS.CHARACTERS.MIOTAN.ANNOUNCE_TOOMANYBIRDS = _G.STRINGS.CHARACTERS.WICKERBOTTOM.ANNOUNCE_TOOMANYBIRDS
_G.STRINGS.CHARACTERS.MIOTAN.ANNOUNCE_WAYTOOMANYBIRDS = _G.STRINGS.CHARACTERS.WICKERBOTTOM.ANNOUNCE_WAYTOOMANYBIRDS

-- staring info
_G.TUNING.GAMEMODE_STARTING_ITEMS.DEFAULT.MIOTAN={"nightmarefuel","nightmarefuel","nightmarefuel","nightmarefuel"}
_G.TUNING.MIOTAN_HUNGER = 100
_G.TUNING.MIOTAN_SANITY = 100
_G.TUNING.MIOTAN_HEALTH = 100